name: 'Action Discord Alerts'
description: 'Send messages with Github Actions CI status to Discord'
author: "ErnaneJ"

inputs:
  webhook:
    description: "Discord webhook."
    required: true
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}
  content:
    description: "Standard message outside the information card. Can be used to mention users."
    required: false
  title:
    description: "For custom title only. By default it is filled with action job status."
    required: false
  description:
    description: "For custom description only. By default it is filled with author and commit message."
    required: false
  image:
    description: "Url of an Image that will be attached to the information card"
    required: false
  thumbnail:
    description: "Url of an thumbnail that will be attached to the information card"
    required: false
  color:
    description: "Overwrite the defined color for the info card highlight. By default this color is set by job status."
    required: false
  username:
    description: "Overrides Discord webhook username. By default we have Github Action."
    required: false
  avatar_url:
    description: "Overrides Discord webhook avatar url. By default we have Github image url."
    required: false
  event_info:
    description: "Decide whether or not to display drill-downs for some information. By default it is shown."
    required: false
    default: true
  timestamp:
    description: "Controls whether to show the timestamp on the info card. Default pos is shown."
    required: false
    default: true
  verbose:
    description: "Controls the sampling of some information when the script runs. For example, the payload that is assembled before being sent to discord."
    required: false
    default: false
  code_coverage:
    description: "Describe the code coverage of the CI of the repository"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  color: "gray-dark"
  icon: "send"