name: CI

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.3.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.1'
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Action Discord Alert
        if: always()
        uses: Thiteago/action-discord-alerts@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}     
          status: ${{ job.status }}
          custom_fields: |
            [
              {"name": "Test Results", "value": "All tests passed", "inline": true},
              {"name": "Duration", "value": "2m 15s", "inline": true}
            ]