name: CI

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Action Discord Alert
        if: always()
        uses: Thiteago/action-discord-alerts@coverage
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}     
          status: ${{ job.status }}
          code_coverage: '55%'