name: CI

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Action Discord Alert
        if: always()
        uses: ErnaneJ/action-discord-alerts@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}     
          status: ${{ job.status }}